baseurl = "https://vikasontech.netlify.com"
title = "Vikas Blogs"
theme = "erblog"
paginate = 10
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "Vikas Verma"
    logo  = "/self/img/avatar.jpg"
    # logo = "//blog.ertuil.top/avater.png"
    bio = """
    <p>Passionate developer with 9+ years of development experience. Certified Professional Scrum Master, Blogger.</p>
    <br/>
    <p>#java #PSM #kotlin #scala #springboot #reactiveProgramming, #functionalProgramming</p>
    <br/><p>Welcome to my world</p>
    """
    copyright = "Copyright © 2019–2020, Vikas Verma"

#[[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 10

[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.icon]]
    name= "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/vikasontech/"
[[menu.icon]]
    name = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/vikas_verma_on/"
[[menu.icon]]
    name = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/vikaskumarverma/"
[[menu.icon]]
    name = "far fa-envelope-open"
    weight = 4
    url = "mailto:vikason@gmail.com"
[[menu.icon]]
    name = "fab fa-rss fa-2x"
    weight = 5
    url = "index.xml"
    rel = "alternate"
    type = "application/rss+xml"

[readingTime]
one = "One minute to read"
other = "{{.Count}} minutes to read"

